// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrQNQMpiZP6BMkasENIamDZTeNJjYQYA',
    appId: '1:473860451308:web:189a4ad051ce93f6446ec9',
    messagingSenderId: '473860451308',
    projectId: 'helpdesk-ti-4bbf2',
    authDomain: 'helpdesk-ti-4bbf2.firebaseapp.com',
    storageBucket: 'helpdesk-ti-4bbf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfH9O3AQ2Hs9-SMHDsA1oyL3m0Hp6IKsw',
    appId: '1:473860451308:android:ae72f8cd46a86c3e446ec9',
    messagingSenderId: '473860451308',
    projectId: 'helpdesk-ti-4bbf2',
    storageBucket: 'helpdesk-ti-4bbf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcJq1GpwpbVTFnQkf1dmkS4LGrHPdFos',
    appId: '1:473860451308:ios:adb279f61fd1c9d9446ec9',
    messagingSenderId: '473860451308',
    projectId: 'helpdesk-ti-4bbf2',
    storageBucket: 'helpdesk-ti-4bbf2.firebasestorage.app',
    iosBundleId: 'com.example.helpdeskTi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcJq1GpwpbVTFnQkf1dmkS4LGrHPdFos',
    appId: '1:473860451308:ios:adb279f61fd1c9d9446ec9',
    messagingSenderId: '473860451308',
    projectId: 'helpdesk-ti-4bbf2',
    storageBucket: 'helpdesk-ti-4bbf2.firebasestorage.app',
    iosBundleId: 'com.example.helpdeskTi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOrQNQMpiZP6BMkasENIamDZTeNJjYQYA',
    appId: '1:473860451308:web:cb260d211ecf6107446ec9',
    messagingSenderId: '473860451308',
    projectId: 'helpdesk-ti-4bbf2',
    authDomain: 'helpdesk-ti-4bbf2.firebaseapp.com',
    storageBucket: 'helpdesk-ti-4bbf2.firebasestorage.app',
  );
}
